"use client";
import "bootstrap/dist/css/bootstrap.min.css";
// import "@/app/assets/css/app.css";
import localFont from "next/font/local";
import "./globals.css";
import router from "next/navigation";
import { ContextProvider } from "./context/contextProvider";
import Head from "next/head";
import { useEffect } from "react";
import BootstrapClient from "@/components/BootstrapClient.js";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    // Function to open the overlay navigation
    function openNav() {
      document.getElementById("myNav").style.height = "100%";
    }

    // Function to close the overlay navigation
    function closeNav() {
      document.getElementById("myNav").style.height = "0%";
    }
  }, []);

  return (
    <html lang="en">
      <Head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Notex - Corporate Business Bootstrap 5 Template</title>
        <link rel="icon" href="/assets/img/favicon.png" sizes="16x16" />
        <link
          rel="stylesheet"
          href="/assets/libs/bootstrap/dist/css/bootstrap.min.css"
        />

        <link
          rel="stylesheet"
          href="/assets/libs/magnific-popup/dist/magnific-popup.css"
        />
        <link
          rel="stylesheet"
          href="/assets/libs/owl.carousel/dist/assets/owl.carousel.css"
        />
        <link
          rel="stylesheet"
          href="/assets/libs/owl.carousel/dist/assets/owl.theme.default.css"
        />
        <link
          rel="stylesheet"
          href="/assets/libs/%40fortawesome/fontawesome-free/css/all.css"
        />
        <link rel="stylesheet" href="/assets/libs/sal.js/dist/sal.css" />
        <link rel="stylesheet" href="/assets/fonts/fonts.css" />
        <link rel="stylesheet" href="/assets/css/app.css" />
      </Head>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ContextProvider>{children}</ContextProvider>

        <BootstrapClient />
        {/* <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
          strategy="beforeInteractive"
        /> */}
      </body>
    </html>
  );
}
